package ${groupId};

/**
 * Hello world!
 *
 */
public class App {
    public static void main( String[] args ) {
        System.out.println( "Hello World!" );
        System.out.println( "This is generated by codegen-maven-plugin" );
        //TODO 写一个codegen-maven-plugin的简介
    }
}
